// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"echo-get-started/driver"
	"echo-get-started/rest/handler"
	"echo-get-started/use_case"
)

// Injectors from wire.go:

func InitNounHandler() *handler.NounHandler {
	nounPort := driver.NewNounPort()
	nounUseCase := use_case.NewNounUseCase(nounPort)
	nounHandler := handler.NewNounHandler(nounUseCase)
	return nounHandler
}
