apiVersion: v1
metadata:
  name: {{ .Values.name }}-svc
  namespace: {{ .Values.namespace }}
kind: Service
spec:
  ports:
  - name: http
    protocol: TCP
    port: 3008
    targetPort: 3008
  type: NodePort
  selector:
    app: {{ .Values.name }}
